print("Line 1: Hello there!")
print("Line 2: This is a random Python script.")
print("Line 3: Just printing some stuff...")
print("Line 4: Nothing too serious.")
print("Line 5: The end. 🎉")
print("Line 6: The updated code base")
