name: Hit API on Commit to Main

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Hit TCU Endpoint
      - run: |
          curl --fail --silent --show-error \
               -X GET "https://6lfl815g-4000.inc1.devtunnels.ms/pull-code" \
               -H "Content-Type: application/json"
